apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mvp-test-component
  namespace: mvp-demo-dev-namespace-nbxm-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/test-images@sha256:9840b4f69275f0fc585f11cacf30264e220b12cb5050710dddefe5bdeaa30d28
        name: container-image
        resources: {}
status: {}
